// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TournamentApi.Models;

namespace TournamentAPI.Migrations
{
    [DbContext(typeof(TournamentContext))]
    [Migration("20191223115026_logo")]
    partial class logo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("TournamentApi.Models.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("InGameName");

                    b.Property<string>("Region");

                    b.Property<long?>("TeamId");

                    b.Property<string>("Username");

                    b.Property<int?>("userId");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("userId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("TournamentApi.Models.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<long?>("OwnerId");

                    b.Property<string>("Region");

                    b.Property<long?>("TournamentId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("TournamentApi.Models.Tournament", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Capacity");

                    b.Property<string>("Description");

                    b.Property<string>("Logo");

                    b.Property<string>("Name");

                    b.Property<string>("Region");

                    b.Property<DateTime>("Start");

                    b.Property<long?>("WinnersId");

                    b.HasKey("Id");

                    b.HasIndex("WinnersId");

                    b.ToTable("Tournament");
                });

            modelBuilder.Entity("TournamentApi.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("Role");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TournamentApi.Models.Player", b =>
                {
                    b.HasOne("TournamentApi.Models.Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId");

                    b.HasOne("TournamentApi.Models.UserInfo", "user")
                        .WithMany()
                        .HasForeignKey("userId");
                });

            modelBuilder.Entity("TournamentApi.Models.Team", b =>
                {
                    b.HasOne("TournamentApi.Models.Player", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("TournamentApi.Models.Tournament")
                        .WithMany("participants")
                        .HasForeignKey("TournamentId");
                });

            modelBuilder.Entity("TournamentApi.Models.Tournament", b =>
                {
                    b.HasOne("TournamentApi.Models.Team", "Winners")
                        .WithMany()
                        .HasForeignKey("WinnersId");
                });
#pragma warning restore 612, 618
        }
    }
}
